language: php

php:
  - 7.2

install:
  - composer validate
#  - composer self-update
  - composer install --prefer-dist --no-progress

script:
  - ./vendor/bin/phpunit -c ./phpunit.xml --coverage-text --verbose