<?php

declare(strict_types=1);
/**
 * ResultProductTest
 *
 * @copyright Copyright © 2020 Rapid dive. All rights reserved.
 * @author    Rapid Dive <rapiddive1@gmail.com>
 */

namespace Rapiddive\Icecat\Tests\Model;

use Rapiddive\Icecat\Model\ResultProduct;
use Rapiddive\Icecat\Tests\FetchProductTest;

class ResultProductTest extends FetchProductTest
{
    /**
     * @var ResultProduct
     */
    private $resultProduct;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->resultProduct = new ResultProduct($this->getXml());
    }

    public function testGetBaseData()
    {
        $this->assertEquals(json_decode(json_encode($this->getXml())), $this->resultProduct->getBaseData());
    }
}
